replicaCount: 2

image:
  repository: ВАШТАКАУНТ.dkr.ecr.eu-north-1.amazonaws.com/lesson-7-django-app
  pullPolicy: Always
  tag: "latest"

nameOverride: ""
fullnameOverride: ""

service:
  type: LoadBalancer
  port: 80
  targetPort: 8000

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 6
  targetCPUUtilizationPercentage: 70

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 256Mi


config:
  SECRET_KEY: "django-insecure-u(qc9*j0w=ut5db3f#izfz_8szd7rruds!p8p5hgwz0in=+s7t"
  DEBUG: "False"
  ALLOWED_HOSTS: "localhost,.eu-north-1.elb.amazonaws.com"
  POSTGRES_DB: "myproject"
  POSTGRES_USER: "myuser"
  POSTGRES_PASSWORD: "mypassword"
  POSTGRES_HOST: "postgres"
  POSTGRES_PORT: "5432"


postgresql:
  enabled: true
  image:
    repository: postgres
    tag: "13"
  
  persistence:
    enabled: true
    size: 8Gi
  
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 250m
      memory: 256Mi

nodeSelector: {}
tolerations: []
affinity: {}